# Generated by Django 6.0.7 on 2026-07-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_seed_initial_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inactive_reason',
            field=models.CharField(blank=True, choices=[('CONTRIBUTION_ARREARS', 'Contribution Arrears')], editable=False, help_text='Reason the member is currently inactive. Automatically maintained by the Member Status Engine.', max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='withdrawal_reason',
            field=models.TextField(blank=True, editable=False, help_text='Reason recorded when a member formally withdraws from FCU.'),
        ),
        migrations.AddField(
            model_name='member',
            name='withdrawn_date',
            field=models.DateField(blank=True, editable=False, help_text='Effective date the member officially withdrew from FCU.', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, help_text='Leave blank (NULL) until the member provides a real email. Members without an email cannot activate an online account (FR-2.2).', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_designated_admin',
            field=models.BooleanField(default=False, help_text='Seed-time flag only. When this member activates an account, the Administrator role is automatically assigned.'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_code',
            field=models.CharField(db_index=True, editable=False, help_text='Permanent, system-generated identifier. Never edited or reused (FR-1.2).', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National Identification Number recorded on the Loan Application Form.', max_length=30, verbose_name='NIN'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='ACTIVE', editable=False, help_text='ACTIVE and INACTIVE are maintained automatically by the Member Status Engine. WITHDRAWN is a permanent administrative status applied when a member formally exits FCU.', max_length=10),
        ),
    ]
