# Generated by Django 6.0.7 on 2026-07-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0003_seed_initial_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, help_text='Null only for a technical break-glass superuser created via createsuperuser (e.g. initial deployment bootstrapping). Every real member-facing account (Member/Treasurer/Chairperson/Secretary/Administrator) must have one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='members.member'),
        ),
    ]
