# Generated by Django 6.0.7 on 2026-07-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_member'),
        ('members', '0003_seed_initial_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member',
            field=models.OneToOneField(blank=True, help_text='Leave blank only for a technical deployment superuser. Every FCU member account must be linked to one Member record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='members.member'),
        ),
    ]
