# Generated by Django 6.0.7 on 2026-07-12 20:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('members', '0003_seed_initial_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('MONTHLY', 'Monthly Contribution'), ('EMERGENCY', 'Emergency Contribution')], help_text='Manual §1.1 defines a Contribution as including both the monthly savings payment and the Emergency Fund payment. They are tracked separately because a member may pay one and not the other, and the Emergency Fund is ring-fenced under §6.1.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount actually paid — not the amount due. Partial payments are legitimate and are stored as separate rows; the shortfall is derived, never stored.', max_digits=12)),
                ('period_month', models.DateField(help_text='WHICH month this payment settles, normalised to the 1st of that month. Distinct from payment_date: Manual §3.2 lets a month be paid up to the 5th of the following month, so a June contribution may legitimately carry a July payment_date.')),
                ('payment_date', models.DateField(help_text='WHEN the money was received. Used to judge lateness against Manual §3.2.')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money')], help_text='How the money reached FCU.', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Optional. Mobile-money transaction ID, bank slip number, or receipt number — whatever lets this row be traced back to a real movement of money.', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Optional free text, e.g. an explanation for a part payment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(help_text='The Financial Cycle this contribution counts toward.', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='cycles.cycle')),
                ('member', models.ForeignKey(help_text='The Member whose contribution this is.', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='members.member')),
                ('recorded_by', models.ForeignKey(help_text='The Treasurer or Administrator who entered this row (Manual §10.1).', on_delete=django.db.models.deletion.PROTECT, related_name='contributions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['member'], name='contributio_member__09baa1_idx'), models.Index(fields=['cycle'], name='contributio_cycle_i_5dc3cd_idx'), models.Index(fields=['payment_date'], name='contributio_payment_d14fde_idx'), models.Index(fields=['contribution_type'], name='contributio_contrib_c9acd9_idx'), models.Index(fields=['member', 'cycle'], name='contributio_member__eb3d6c_idx'), models.Index(fields=['member', 'cycle', 'contribution_type', 'period_month'], name='contributio_member__d5cf99_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='contributions_amount_greater_than_zero')],
            },
        ),
    ]
