# Generated by Django 6.0.7 on 2026-07-09 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed login'), ('LOGOUT', 'Logout'), ('STATUS_CHANGE', 'Status change'), ('ROLE_CHANGE', 'Role change'), ('SETTINGS_CHANGE', 'Settings change'), ('ACCOUNT_ACTIVATED', 'Account activated')], max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null for system-initiated actions or anonymous failed logins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auditlog_au_timesta_a26c2b_idx'), models.Index(fields=['model_name', 'object_id'], name='auditlog_au_model_n_f1dd52_idx'), models.Index(fields=['actor'], name='auditlog_au_actor_i_db4f8d_idx')],
            },
        ),
    ]
