# Generated by Django 6.0.7 on 2026-07-09 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('LOAN_APPLICATION_FORM', 'Loan Application Form'), ('MEMBER_DECLARATION', 'Member Declaration & Commitment Agreement')], max_length=32)),
                ('file', models.FileField(upload_to='document_templates/')),
                ('version_label', models.CharField(help_text='e.g. "v1.0"', max_length=20)),
                ('is_current', models.BooleanField(default=True, help_text='Only one template per doc_type should be current; uploading a new one supersedes the last.')),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
