# Generated by Django 6.0.7 on 2026-07-11 18:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Calendar year, e.g. 2026.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financial year',
                'verbose_name_plural': 'Financial years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(help_text="Sequential across FCU's whole history: Cycle 1, Cycle 2, ... Never reused.", unique=True)),
                ('name', models.CharField(blank=True, help_text='e.g. "January-June 2026". Left blank, it is generated from the dates.', max_length=100)),
                ('start_date', models.DateField(help_text='First day the cycle covers.')),
                ('duration_months', models.PositiveSmallIntegerField(default=6, help_text='Manual 2.1(b) fixes a Financial Cycle at 6 months. Anything else requires a written override reason below.')),
                ('duration_override_reason', models.TextField(blank=True, help_text='Mandatory whenever duration_months is not 6. Recorded in the audit log. Exists mainly to allow the historical Cycles 1-4 import to reflect what actually happened.')),
                ('end_date', models.DateField(editable=False, help_text='Derived: last day of the final month of the cycle.')),
                ('monthly_savings_amount', models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Manual 3.1 - UGX 100,000. Amendable only by General Meeting resolution (11.4).', max_digits=12)),
                ('monthly_emergency_amount', models.DecimalField(decimal_places=2, default=Decimal('5000'), help_text='Manual 3.1 / 6.1 - UGX 5,000. Amendable only by General Meeting resolution (11.4).', max_digits=12)),
                ('per_member_target', models.DecimalField(decimal_places=2, editable=False, help_text='Derived: (monthly savings + monthly emergency) x duration_months.', max_digits=14)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='UPCOMING', editable=False, help_text='Changed only through activate() / close() / reopen(), never edited directly.', max_length=10)),
                ('active_singleton', models.BooleanField(default=None, editable=False, null=True)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('reopen_count', models.PositiveSmallIntegerField(default=0, editable=False, help_text='How many times this cycle has been reopened after closing. Should stay 0.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_activated', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_closed', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(editable=False, help_text='Derived from start_date - not entered by hand.', on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='cycles.financialyear')),
            ],
            options={
                'ordering': ['-cycle_number'],
                'constraints': [models.UniqueConstraint(fields=('active_singleton',), name='cycles_only_one_active_cycle'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='cycles_end_date_after_start_date'), models.CheckConstraint(condition=models.Q(('duration_months__gte', 1)), name='cycles_duration_at_least_one_month')],
            },
        ),
    ]
